from __future__ import annotations
import typing as typ

class timespec:
    sec: int
    nsec: int

class processinfo:
    @typ.overload
    def __init__(self) -> None: ...
    @typ.overload
    def __init__(self, name: str, CTRLval: int) -> None: ...

    def __init__(self, name: str = '', CTRLval: int = -1) -> None: ...


    def create(self, name: str, CTRLval: int) -> int: ...
    def link(self, name: str) -> int: ...
    def close(self, name: str='') -> int: ...
    def sigexit(self, sig: int) -> int: ...

    def writeMessage(self, message: str) -> int: ...

    def exec_start(self) -> int: ...
    def exec_end(self) -> int: ...

    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...

    @property
    def source_function(self) -> str: ...
    @source_function.setter
    def source_function(self, value: str) -> None: ...

    @property
    def source_FILE(self) -> str: ...
    @source_FILE.setter
    def source_FILE(self, value: str) -> None: ...

    @property
    def source_LINE(self) -> int: ...
    @source_LINE.setter
    def source_LINE(self, value: int) -> None: ...

    @property
    def PID(self) -> int: ...
    @PID.setter
    def PID(self, value: int) -> None: ...

    # TODO: this could just be a pass-by-timestamp.
    @property
    def create_time(self) -> timespec: ...
    @create_time.setter
    def create_time(self, value: timespec) -> None: ...

    @property
    def loopcnt(self) -> int: ...
    @loopcnt.setter
    def loopcnt(self, value: int) -> None: ...

    @property
    def CTRLval(self) -> int: ...
    @CTRLval.setter
    def CTRLval(self, value: int) -> None: ...

    @property
    def tmuxname(self) -> str: ...
    @tmuxname.setter
    def tmuxname(self, value: str) -> None: ...

    @property
    def loopstat(self) -> int: ...
    @loopstat.setter
    def loopstat(self, value: int) -> None: ...

    @property
    def statusmsg(self) -> str: ...
    @statusmsg.setter
    def statusmsg(self, value: str) -> None: ...

    @property
    def statuscode(self) -> int: ...
    @statuscode.setter
    def statuscode(self, value: int) -> None: ...

    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, value: str) -> None: ...
